artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/957801158650053421/2f95cad090fc419fbb7672757848e4b0/artifacts
end_time: 1783703225776
entry_point_name: ''
experiment_id: '957801158650053421'
lifecycle_stage: active
run_id: 2f95cad090fc419fbb7672757848e4b0
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783695537742
status: 3
tags: []
user_id: root
