type: order_cards
visible: false
header: Variance of Sum
text: Order the cards to reconstruct variance of sum proof
shuffle: true
score: 2
quiz:
  variants:
    - text: >
        Opening the brackets, we will get:

        $$\mathbb V (a \xi + b \eta) =\mathbb E (a^2 \xi^2) + \mathbb E (2 a \xi
        b \eta) + \mathbb E (b \eta)^2 - (\mathbb E (a \xi))^2 - 2 \mathbb E a
        \xi \mathbb E b \eta - (\mathbb E (b \eta))^2$$
    - text: >
        Taking out the coefficients, we get:

        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb E \xi^2 +2 a b \mathbb
        E  (\xi \eta) + b^2 \mathbb E \eta^2 - a^2 (\mathbb E \xi)^2 - 2 a b
        \mathbb E \xi \mathbb E \eta - b^2(\mathbb E \eta)^2$$
    - text: >
        If we have independent $\xi$ and $\eta$, then

        $$\mathbb E \xi \eta = \sum_{k} x_k y_k p(x_k, y_k) = \sum_{k} x_k y_k
        p(x_k)p(y_k) = \sum_{k} x_k p(x_k) \sum_{k} y_k p(y_k) = \mathbb E \xi
        \mathbb E \eta$$
    - text: |
        Now consider $$\mathbb V (a \xi + b \eta)$$
    - text: |
        In that case the two last terms are cancelled, and we get:
        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb V \xi + b^2 \mathbb V \eta$$
    - text: |
        Simplifying the expression above, we will get:
        $$\mathbb V \xi = \mathbb E \xi^2 - (\mathbb E \xi)^2$$
    - text: >
        Recalling that $\mathbb V \xi = \mathbb E \xi^2 - (\mathbb E \xi)^2$:

        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb V \xi + b^2 \mathbb V \eta +
        2 a b \mathbb E  (\xi \eta) - 2 a b \mathbb E \xi \mathbb E \eta$$
    - text: |
        Note that this expression is correct for any $\xi$ !!!
    - text: >
        In fact, $\mathbb E \xi$ is a constant (as it is kind of average value),
        thus:

        $$\mathbb V \xi = \mathbb E \xi^2 - 2 (\mathbb E \xi)^2 + (\mathbb E
        \xi)^2$$
    - text: >
        Take the formula that was proven above, and we will get:

        $$\mathbb V (a \xi + b \eta) =\mathbb E (a \xi + b \eta)^2 - (\mathbb E
        (a \xi + b \eta))^2$$
    - text: >
        Opening the brackets and thinking about $\mathbb E$ as about the
        average, we will get:

        $$\mathbb V \xi = \mathbb E (\xi^2 - 2 \xi \mathbb E \xi + (\mathbb E
        \xi)^2)$$
    - text: |
        Start with definition of $\mathbb V \xi$,
        $$\mathbb V \xi = \mathbb E (\xi - \mathbb E \xi)^2$$
answer:
  - 57a0726e0152e6875b7ffa5b01370b07
  - 0fd8ac09097a54a35f6b1f42b0bbd4ff
  - 67f3eae54b91af205c7221c64800646c
  - bddf1a6f0253e5049a58cf761a6f5136
  - 92b61626be70d77407aa0233531334d7
  - 843e9b8e0eb10e983e120819f583d565
  - 10ee21d75f036049052cf1d5765fc609
  - fec5703a4ef6eeab2cd1cee0946f6cbf
  - d78d20a3377765788e1289f730e9226c
  - 5db808dd656143d5c55a0d3b7897a04d
  - ae243f297c71e267588c1c9df466daa2
  - 638e0edf52cc01bc5475ad7eba1a2125
