artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/957801158650053421/488e18a1f4a24a54ad1e02707ced3685/artifacts
end_time: 1783602413199
entry_point_name: ''
experiment_id: '957801158650053421'
lifecycle_stage: active
run_id: 488e18a1f4a24a54ad1e02707ced3685
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783601743372
status: 3
tags: []
user_id: root
