order:
  - 1. Linearity of Expectation
  - 2. Variance of Sum
  - 3. Random Variables and Covariance
  - 4. Discrete Probability Practice
  - 5. Maximal Likelihood of Normal Distribution
  - 6. Maximal Likelihood of Multivariate Normal Distribution
