artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/957801158650053421/df8d4a1189a84860a52ec49e3da14885/artifacts
end_time: 1783613346049
entry_point_name: ''
experiment_id: '957801158650053421'
lifecycle_stage: active
run_id: df8d4a1189a84860a52ec49e3da14885
run_name: autoencoder_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783612911479
status: 3
tags: []
user_id: root
